### PR TITLE
Add edit trade, fix some stuff and optimizations.

### PR DESCRIPTION
**Pull request by spinningtoilet0**
idk i just thought i might code this cuz i was bored LMAO

### CODE REVIEW

**Review by AutumnHW — CHANGES_REQUESTED** [review]
Currently the initial trade feature is not complete, so the json file structure isnt explicitely ready. to edit order data you would need to read from and write to these json files correctly. i cant really give you a specific direction to take your files as far as the syntax goes yet but id wait a few days until i get done with the filestructure of <ordernumber>.json. keep in mind though that to make these commands work the order number must be specified in the command for it to be able to retrieve the right json file.

**Review by AutumnHW — COMMENTED** [review]
wait never mind you completed sendtrade.js MY BAD!!!

**Comment by AutumnHW** [comment]
also holy fuck this is some shit ive not seen before, nice work!

**Comment by AutumnHW** [comment]
right ill review all this in a production enviroment in the morning. Overall amazing work my dude!

**Comment by spinningtoilet0** [comment]
code should be ready now! let me know if there is any issues.

**Pull request merged**
